#!/bin/bash
brew install --verbose --build-bottle Formula/"$PACKAGE".rb
brew bottle $PACKAGE --json --force-core-tap
brew install jq
bottleJson=$( cat *.json )
FILENAME=$(echo $bottleJson | jq --raw-output '."'henkrehorst/bc/"$PACKAGE"'"."bottle".tags.'"$OS"'.filename')
echo $FILENAME
LOCALFILE=$(echo $bottleJson | jq --raw-output '."'henkrehorst/bc/"$PACKAGE"'"."bottle".tags.'"$OS"'.local_filename')
echo $LOCALFILE
ls -all
#         Transfer to bintray
curl -T $LOCALFILE -uhenkrehorst:$BINTRAY_KEY https://api.bintray.com/content/henkrehorst/homebrew-bc/homebrew-bc/homebrew-bc/$FILENAME
curl -T *.json -uhenkrehorst:$BINTRAY_KEY https://api.bintray.com/content/henkrehorst/homebrew-bc/homebrew-bc/homebrew-bc/new@$PACKAGE.$OS.json
